# Cap. 2, Sec. 0 #
### Introduction to NumPy ###

In [5]:
import numpy

In [5]:
numpy.__version__

'1.16.4'

In [6]:
import numpy as np

# Cap. 2, Sec. 1 #
### Understanding Data Types in Python ###

* Ejemplo en C

int r=0;

for (int i=0; i<100; i++}

{ r+=i; }

* Ejemplo en python

In [1]:
r=0
for i in range(100):
    r+=i

* Tipos de variable inferidos dinámicamente 

In [7]:
x=3
x="tres"

* Listas y asignación de los tipos de valiable de sus elementos

In [9]:
L=list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
type(L[0])

int

* Una lista de "strings"

In [12]:
L2=[str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(L2[3])

str

* Una lista con una combinación heterogenea de tipos de variables

In [15]:
L3=[True, 2.0 , 3, "4"]
[type(i) for i in L3]

[bool, float, int, str]

* Usando "array" para crear arreglos de un tipo de variable fijo

In [19]:
import array
L=list(range(10))
A=array.array("i", L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* Creando arreglos de numpy

In [20]:
import numpy as np

In [22]:
np.array([range(10)])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

* Los arreglos de numpy tienen un tipo de variable fijo a fin de reducir el uso de memoria. Por ello al tener solo un float todos los elementos del arreglo pasan a serlo

In [25]:
np.array([1, 2, 3, 4.5])

array([1. , 2. , 3. , 4.5])

* Se puede elejir de forma explícita el tipo de variable del arreglo

In [26]:
np.array([1,2,3,4],dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [28]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

* Creando arreglos de tamaño dado llenos con un valor y un tipo de variable específicos

In [29]:
np.zeros(8, dtype=int)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* Llenando él arreglo con un valor personalizado

In [31]:
np.full((2, 4), 4.11)

array([[4.11, 4.11, 4.11, 4.11],
       [4.11, 4.11, 4.11, 4.11]])

* O llenandolo con una secuencia lineal de intervalo personalizable

In [38]:
np.arange(0, 16, 3)

array([ 0,  3,  6,  9, 12, 15])

* O una cantidad determinada de elementos distribuidos en un intervalo

In [39]:
np.linspace(0, 1, 8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

* Arreglo relleno con valores aleatorios entre 0 y 1

In [41]:
np.random.random((3,3))

array([[0.99139927, 0.74532733, 0.81392335],
       [0.63946842, 0.81039526, 0.29964512],
       [0.06006319, 0.85503271, 0.58237934]])

* Similar pero con una media y desviación estándar dadas

In [42]:
np.random.normal(0,2, (4,4))

array([[ 0.24711923,  0.48083848, -0.51505104, -4.21875917],
       [ 0.38555193,  3.90091675, -0.94865566, -2.38022398],
       [ 0.9393923 , -1.53448923,  0.21636696,  1.79404948],
       [-0.36565325, -2.51801476, -3.02571011,  2.14707402]])

* Arreglo de enteros aleatorios

In [43]:
np.random.randint(0,10,(2,4))

array([[9, 6, 5, 7],
       [6, 4, 2, 7]])

* Una matriz identidad

In [44]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

* Un arreglo sin inicializar

In [45]:
np.empty(3)

array([3.31033942e-33, 6.97666413e-76, 3.45618036e-86])

# Cap. 2, Sec.2 #
### The Basics of NumPy Arrays ###

* Creando 3 arreglos aleatorios de diferente dimensión y usando la instrucción "seed" para asegurar la reproducibilidad

In [46]:
import numpy as np
np.random.seed(0)
x1=np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5)) 

* Cada arreglo tiene los atributos de número de dimensiones, tamaño de las dimensiones y tamaño total

In [48]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


* Se puede leer también el tipo de variable de un arreglo determinado

In [49]:
print("Tipo de variable de x3:", x3.dtype)

Tipo de variable de x3: int64


* O el tamaño en Bytes de cada elemento o del areeglo completo

In [50]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


* Se pueden leer los valores de un elemento específico de un arreglo

In [51]:
x1

array([5, 0, 3, 3, 7, 9])

In [52]:
x1[3]

3

In [53]:
x1[0]

5

* Es posible identificar los elementos en sentido inverso con índices negativos

In [54]:
x1[-1]

9

In [55]:
x1[-6]

5

* En areeglos de dimensión mayor deben indicarse ambos índices

In [56]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [57]:
x2[0,0]

3

In [58]:
x2[2,3]

7

In [60]:
x2[-1,3]

7

In [61]:
x2[0,1]=4

In [62]:
x2

array([[3, 4, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

* No se piede insertar un tipo de variable que no sea el correspondiente al arreglo

In [69]:
x2[0,0]=7.1

In [70]:
x2[0,0]

7

* Se puede acceder a sub-arreglos dentro de un arreglo específico

In [72]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x[:5]

array([0, 1, 2, 3, 4])

In [75]:
x[5:]

array([5, 6, 7, 8, 9])

In [76]:
x[4:7]

array([4, 5, 6])

In [77]:
x[::2]

array([0, 2, 4, 6, 8])

In [78]:
x[1::2]

array([1, 3, 5, 7, 9])

* Los valores de intervalo negativo recorren en sentido opuesto el arreglo

In [79]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [80]:
x[5::-2]

array([5, 3, 1])

* En los sub-arreglos multi-dimensionales se separa cada dimensión por una coma

In [81]:
x2

array([[7, 4, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [82]:
x2[:2, :3]

array([[7, 4, 2],
       [7, 6, 8]])

In [83]:
x2[:3, ::2]

array([[7, 2],
       [7, 8],
       [1, 7]])

In [84]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 4, 7]])

* Se pueden aislar filas o columnas específicas de un arreglo multi-dimensional

In [85]:
print(x2[:, 0])

[7 7 1]


In [86]:
print(x2[0, :])

[7 4 2 4]


* Suprimeindo una fila o columna de forma más compacta

In [87]:
print(x2[0])

[7 4 2 4]


* Modificar los arreglos definidos como sub-arreglos de otros modifica al original

In [88]:
print(x2)

[[7 4 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [89]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[7 4]
 [7 6]]


In [90]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  4]
 [ 7  6]]


In [91]:
print(x2)

[[99  4  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


* Con el comando "copy" el arreglo copia no modifica el original

In [92]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  4]
 [ 7  6]]


In [93]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  4]
 [ 7  6]]


In [94]:
print(x2)

[[99  4  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


* Con la instucción "reshape" se puede modificar la forma de un arreglo, incluyendo su dimensión

In [95]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* Usando "newaxis" se convierte un arreglo uni-dimensional a uno bi-dimensional columna o fila

In [96]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [97]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [98]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [99]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

* El comando "concatenate" justamente concatena, o combina, dos arreglos

In [100]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [101]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [102]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [103]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [104]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* Para arreglos multi-dimensionales puede ser mas claro usar las instrucciones "vstack" y "hstack"

In [105]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [106]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

* De forma análoga se pueden separar arreglos con los comandos "split" "hsplit" y "vsplit"

In [107]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [108]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [110]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Cap. 2, Sec, 3 #
### Computation on NumPy Arrays: Universal Functions ###

* Python resulta relativamente lento al realizar un gran número de pequeñas operaciones debido a la forma en la que construye sus variables

In [111]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [112]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

3.05 s ± 23.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


* Usando operaciones vectorizadas el cálculo debería ser más eficiente

In [113]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [114]:
%timeit (1.0 / big_array)

3.5 ms ± 66.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [115]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [116]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

* Operaciones fundamentales de la aritmética de vectores

In [117]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [118]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [119]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

* El símbolo "+" resume la operación "add"

In [120]:
np.add(x, 2)

array([2, 3, 4, 5])

* También existe la operación de valor absoluto

In [121]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

* La función de numpy equivalente es:

In [122]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [123]:
np.abs(x)

array([2, 1, 0, 1, 2])

* También puede usarse en números complejos

In [124]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

* Numpy también incluye funciones trigonométricas, para usarlas primero hay que definir un arreglo de ángulos

In [125]:
theta = np.linspace(0, np.pi, 3)

In [126]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [127]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


* También existen las funciones exponenciales y logarítmicas

In [128]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [129]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [130]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


* Se pueden realizar productos exteriores entre los arreglos

In [134]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# Cap. 2, Sec. 4 #
### Aggregations: Min, Max, and Everything In Between ###

* COmo primera aproximación a la estadística, python puede sumar todos los valores de un arreglo

In [135]:
import numpy as np

In [136]:
L = np.random.random(100)
sum(L)

50.461758453195614

In [137]:
np.sum(L)

50.46175845319564

* Comparación de los tiempos con y sin numpy

In [138]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

135 ms ± 754 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
802 µs ± 23.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


* Python y numpy cuentan también con funciones para encontrar máximos y mínimos en un arreglo

In [139]:
min(big_array), max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [140]:
np.min(big_array), np.max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [141]:
%timeit min(big_array)
%timeit np.min(big_array)

109 ms ± 4.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
833 µs ± 73.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [142]:
print(big_array.min(), big_array.max(), big_array.sum())

7.071203171893359e-07 0.9999997207656334 500216.8034810001


* Se pueden analizar de forma similar arreglos multi-dimensionales o a través de filas y columnas específicas del mismo

In [143]:
M = np.random.random((3, 4))
print(M)

[[0.79832448 0.44923861 0.95274259 0.03193135]
 [0.18441813 0.71417358 0.76371195 0.11957117]
 [0.37578601 0.11936151 0.37497044 0.22944653]]


In [144]:
M.sum()

5.1136763453287335

In [145]:
M.min(axis=0)

array([0.18441813, 0.11936151, 0.37497044, 0.03193135])

In [146]:
M.max(axis=1)

array([0.95274259, 0.76371195, 0.37578601])